name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: set npm config
        run: npm config set "//npm.pkg.github.com/:_authToken=${TOKEN}" -L project
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci

      - run: npm run build

      - run: npm run test

  install_stable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - id: toolchain
        uses: ./
        with:
          toolchain: stable

      - name: Test toolchain outputs
        env:
          RUSTC: ${{ steps.toolchain.outputs.rustc }}
          RUSTC_HASH: ${{ steps.toolchain.outputs.rustc_hash }}
          CARGO: ${{ steps.toolchain.outputs.cargo }}
          RUSTUP: ${{ steps.toolchain.outputs.rustup }}
        run: |
          echo $RUSTC
          echo $RUSTC_HASH
          echo $CARGO
          echo $RUSTUP

  install_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy

  install_stable_in_docker:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - run: apt-get update && apt-get install -y curl

      - uses: actions/checkout@v3.1.0

      - uses: ./
        with:
          toolchain: stable

  install_stable_through_rust_toolchain_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: echo "stable" > ./rust-toolchain
      - uses: ./
